### ISSUE TITLE
Tarefa 01: Metodologia e Cronograma

### ISSUE THREAD

**Issue by rvenson** [GabrielaMaccarini/Projeto_TCC#2]
Descrever no projeto fictício criado toda a metodologia utilizada para o desenvolvimento do projeto. Isto é: explicar detalhadamente os objetivos específicos.
Em seguida, criar o cronograma de desenvolvimento. Para cada um dos objetivos específicos deve ser estabelecido um prazo. (PRAZO FINAL: Dezembro de 2016)

**Comment by GabrielaMaccarini** [comment]
![erro](https://cloud.githubusercontent.com/assets/20979243/17778292/f0ada436-6539-11e6-86a7-f52bacb149ee.PNG)

Isso é normal? Se eu der stage commit ele vai upar certinho?
Edit: o botão de sign off exclui as mudanças que eu não quero que estejam no push? Não quero que apareçam os dois primeiros arquivos.

**Comment by rvenson** [comment]
Oi Gabriela,
Só vai ser adicionado ao commit aquilo que estiver na caixa Staged Changes. Então você pode selecionar o primeiro e o segundo arquivo e clicar no botão Stage Changed e depois comitar.
